#!/usr/bin/env bash
# Transfer a file to a server
msg = "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
if [ "$#" -ne 4 ]; then
    echo "$msg"
    exit 1
fi
scp -i "$4" "$1" "$3"@"$2":/tmp/
