#!/usr/bin/env bash
# Configure your Nginx server so that /redirect_me is redirecting to another page.

# Install Nginx
apt-get -y update
apt-get -y install nginx

# Create a new file
touch /etc/nginx/sites-available/redirect_me

# Edit the file

server 
{
    listen 80;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    server_name _;
    location /redirect_me 
    {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}

# Create a symbolic link
ln -s /etc/nginx/sites-available/redirect_me /etc/nginx/sites-enabled/redirect_me

# Restart Nginx
service nginx restart
