#!/usr/bin/env bash
# configure ubuntu machine to redirect /redirect_me to https://www.youtube.com/watch?v=QH2-TGUlwu4 with a 301
sudo apt-get update
sudo apt-get install -y nginx

echo "Hello, World!" > /var/www/html/index.html

new_config= "server {
    listen 80 default_server;
    listen [::]:80 default_server;

    add_header X-Served-By $HOSTNAME;

    root /var/www/html;

    index index.html index.htm index.nginx-debian.html;

    server_name _;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}"

echo "$new_config" > /etc/nginx/sites-available/default
service nginx restart
