#!/usr/bin/env bash
# Redirect to a different URL
sudo apt-get update
sudo apt-get install -y nginx
# Create a new file in /etc/nginx/conf.d/ called redirect_me.conf
sudo tee /etc/nginx/conf.d/redirect_me.conf > /dev/null <<EOT
location /redirect_me {
    return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
}
EOT
sudo service nginx restart