#!/usr/bin/env bash
# 404 page not found in nginx

# Upadating Packages before Installations
apt-get update
apt-get install -y nginx

# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html;

echo "server
{
	listen 80 default_server;
	listen [::]:80 default_server;

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	location / {
		root /var/www/html;      
	}

	error_page 404 /404.html;
	location = /404.html {
		root /var/www/html;
		internal;
	}
}" | sudo tee /etc/nginx/sites-available/default

# Restarting Nginx service
nginx -s reload
