#!/usr/bin/bash
# setup redirection for nginx configs
sudo apt-get update
sudo apt-get install -y nginx

sudo service nginx start

sudo ufw allow 'Nginx HTTP'

sudo chown -R "$USER":"$USER" /var/www/html
sudo chmod -R 755 /var/www

cp /var/www/html/index.nginx-debian.html /var/www/html/index.nginx-debian.html.bckp
# Creating an index.html page
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Performing a "moved permanently redirection" (301)
sudo sed -i '24i\    rewrite ^/redirect_me https://www.github.com/mohanned-sameh permanent;' /etc/nginx/sites-available/default

echo "Ceci n'est pas une page" >> /var/www/html/error_404.html
sudo sed -i '25i\    error_page 404 /error_404.html;' /etc/nginx/sites-available/default

# Restart nginx after implementing changes
sudo service nginx restart
