#!/usr/bin/env bash
# install nginx
sudo apt-get update
sudo apt-get install nginx -y

# create index.html
echo "Hello World!" | sudo tee /var/www/html/index.html

# performing a 301 redirect
new_string="server_name_;\n\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
sudo sed -i "s/server_name_/server_name;/$new_string/" /etc/nginx/sites-enabled/default

# create a 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
new_string="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/usr\/share\/nginx\/html;\n\t\tinternal;\n\t}"

sudo sed -i "s/listen 80 default_server;/$new_string/" /etc/nginx/sites-enabled/default

# add header to response
sudo sed -i "/server_name_/a add_header X-Served-By $HOSTNAME;" /etc/nginx/sites-enabled/default

# test nginx
sudo nginx -t

# restart nginx
sudo service nginx restart
