#!/usr/bin/env bash
# install haproxy
sudo apt-get update
sudo apt-get install -y haproxy
echo "frontend web-front
    bind *:80
    default_backend web-back

backend web-back
    balance roundrobin
    server web1 100.26.224.147:80 check
    server web2 34.204.91.116:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
