#!/usr/bin/env bash
# Configure Nginx to run on port 80
# In one shot:
sudo sed -i "s/listen 8080 default_server;/listen 80 default_server;/" /etc/nginx/sites-enabled/default
sudo sed -i '22d' /etc/nginx/sites-enabled/default
sudo service nginx start