#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
sed -i "s/listen 80 default_server;/listen 8080 default_server;/g" /etc/nginx/sites-available/default
sudo service nginx restart
pkill -f nginx