#!/usr/bin/env bash
# Configures an Nginx server to listen on port 80.
sed -i 's/80 default_server/8080 default_server/g' /etc/nginx/sites-available/default
sudo service nginx start
sudo kill "$(pgrep 'nginx' | head -1)"