#!/usr/bin/env bash
# this script manages manage_my_process
# when passing "start" it will start manage_my_process
# creates a file containing its PID in /var/run/manage_my_process.pid
# displays "manage_my_process started"
# when passing "stop" it will stop manage_my_process
# removes the PID file in /var/run/manage_my_process.pid
# displays "manage_my_process stopped"
# when passing "restart" it will stop manage_my_process
# deletes the PID file in /var/run/manage_my_process.pid
# starts manage_my_process
# creates a file containing its PID in /var/run/manage_my_process.pid
# displays "manage_my_process restarted"
# displays "Usage: manage_my_process {start|stop|restart}" when passing an invalid argument

if [ "${1}" == "start" ]
then
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
elif [ "${1}" == "stop" ]
then
	echo "manage_my_process stopped"
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
elif [ "${1}" == "restart" ]
then
	kill "$(cat /var/run/my_process.pid)"
	rm /var/run/my_process.pid
	./manage_my_process &
	touch /var/run/my_process.pid
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
else
	echo "Usage: manage_my_process {start|stop|restart}"
fi