#!/usr/bin/env bash
# This script displays Best School 10 times,
# but for the 9th iteration, displays Best School and
# then Hi on a new line.
number=0
while [ $number -lt 10 ]
do
	if [ $number = 9 ]
	then
		echo "Hi"
	else
		echo "Best School"
	fi
	number=$((number + 1))
done
