#!/usr/bin/env bash
# This script displays numbers from 1 to 20

num=1
while [ $num -lt 21 ]
do
case $num in
    4) echo "$num"
       echo "bad luck from China"
    ;;
    9) echo "$num"
       echo "bad luck from Japan"
    ;;
    17)echo "$num"
       echo "bad luck from Italy"
    ;;
    *)
	echo "$num"
esac
	num=$((num+=1))
done
